- name: Install moodle
  remote_user: ubuntu
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Download and Extract moodle
      unarchive:
        src: https://download.moodle.org/download.php/direct/stable36/moodle-3.6.2.tgz
        dest: /var/www/html
        remote_src: yes
    - name: install dependencies
      command: sudo apt -q -y install libapache2-mod-php 
      command: sudo apt -q -y install mysql-server
      command: sudo apt -q -y install php-mysql 
      command: sudo apt -q -y install php-gd 
      command: sudo apt -q -y install php-intl
      command: sudo apt -q -y install php-xmlrpc
      command: sudo apt -q -y install php-soap
      command: sudo apt -q -y install php-cli
      command: sudo apt -q -y install php-zip
      command: sudo apt -q -y install php-mbstring
      command: sudo apt -q -y install php-curl
      command: sudo apt -q -y install php-xml
      command: sudo apt -q -y install php-pear 
      command: sudo apt -q -y install php-bcmath php-fpm
    - name: Creates directory
      file:
        path: /var/www/html/moodledata
        state: directory
        owner: www-data
        group: www-data
        mode: 0775